services:
  event-service:
    build: ./event-service
    ports:
      - "8081:8081"
  participant-service:
    build: ./participant-service
    ports:
      - "8082:8082"
  ticket-service:
    build: ./ticket-service>
    ports:
      - "8083:8083"
